#!/bin/bash
## FusionFall Retro install script for Linux


## Environment setup and variables.
TEMP_DIR=/tmp/FusionFallRetro_Installer
LAUNCHER_URL='https://cdn.fusionfalluniverse.com/launcher/ULInstaller_x86.exe'
LAUNCHER_DL_NAME="${LAUNCHER_URL##*/}"
[ -z "$WINEPREFIX" ] && export WINEPREFIX=$HOME/.wine
export WINEARCH=win32
export WINEDEBUG=-all

rm -rf $TEMP_DIR
mkdir -p $TEMP_DIR

## Dependency checks
echo '* Checking dependencies...'
{ wine --version | grep -q "Staging"; } && echo 'wine staging OK' || { echo >&2 '! Staging version of wine required.'; exit 1; }
{ command -v setup_dxvk32 >/dev/null 2>&1; } && echo 'DXVK OK' || { echo >&2 "! DXVK 32bit required but not installed. https://github.com/doitsujin/dxvk"; exit 1; }
[ -e '/usr/lib32/libvulkan.so.1' ] && echo 'libvulkan OK' || { echo >&2 "! WARNING: '/usr/lib32/libvulkan.so.1' not found"; }


echo -e '**\n** Welcome to the FusionFall Retro Linux Installer!\n**'


## Check for clean Wine prefix.
if [ -e "$WINEPREFIX" ]; then
    echo '! WARNING: This installer must run on a CLEAN wineprefix. A non-empty prefix was detected.'
    echo '  If you want to handle this yourself, CTRL+C or type "N" at the next prompt.'
    read -p "DELETE the wineprefix located at '$WINEPREFIX'? [y/N] " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        rm -rf $WINEPREFIX || { echo >&2 '! rm failed'; exit 1; }
        echo '* wineprefix cleaned.'
    else
        echo '! Installation canceled.'
        exit 1
    fi
else
    echo '* Clean wineprefix detected.'
fi

## Install libraries
echo '* Setting up wineprefix...'
wineboot --init || { echo >&2 "! wineboot failed"; exit 1; }
sleep 6  # Required to make sure wineboot finished its setup.
setup_dxvk32 || { echo >&2 "! DXVK setup failed :("; exit 1; }
winetricks -q vcrun2015 || { echo >&2 "! Library 'vcrun2015' failed to install :("; exit 1; }
# winetricks -q corefonts || { echo "! Library 'corefonts' failed to install :("; exit 1; }
# winetricks -q crypt32 || { echo "! Library 'crypt32' failed to install :("; exit 1; }


## Run the installer
winetricks win7
echo '* Downloading FFR Installer...'
wget -nv ${LAUNCHER_URL} -O ${TEMP_DIR}/$LAUNCHER_DL_NAME
echo '* Running FFR Installer...'
wine $TEMP_DIR/$LAUNCHER_DL_NAME


## Export desktop file and script for running FFR
cat > $TEMP_DIR/FusionFall\ Universe.desktop <<- EOS
	[Desktop Entry]
	Name=FusionFall Universe
	Exec=env WINEPREFIX="$WINEPREFIX" /usr/bin/wine C:\\\\Program\\ Files\\\\FusionFall\\ Universe\\\\UniverseLauncher.exe 
	Type=Application
	StartupNotify=true
	Path=$WINEPREFIX/dosdevices/c:/Program Files/FusionFall Universe/
	Icon=1DD3_UniverseLauncher.0
	StartupWMClass=universelauncher.exe
EOS
chmod +x $TEMP_DIR/FusionFall\ Universe.desktop
echo "* Desktop file written to '$TEMP_DIR/FusionFall\ Universe.desktop'"
cat > $TEMP_DIR/fusionfall_universe.sh <<- EOS
	#!/bin/sh
	# Automaticaly generated by $0 on $(date)

	cd "$WINEPREFIX/dosdevices/c:/Program Files/FusionFall Universe/"
	env WINEPREFIX="$WINEPREFIX" /usr/bin/wine C:\\\\Program\\ Files\\\\FusionFall\\ Universe\\\\UniverseLauncher.exe 
EOS
chmod +x $TEMP_DIR/fusionfall_universe.sh
echo "* Launch script written to '$TEMP_DIR/fusionfall_universe.sh'"


echo -e "**\n** Installation complete!\n**"
exit 0
